{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronos-db.fullname" . }}-tls
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.tls }}
stringData:
  tls.crt: {{ .cert | default "" | quote }}
  tls.key: {{ .key | default "" | quote }}
  ca.crt: {{ .caCert | default "" | quote }}
{{- end }}
---
{{- end }}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronos-db.fullname" . }}-auth
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.auth }}
stringData:
  {{ .secretKey | default "jwt-secret" }}: {{ .jwtSecret | default "" | quote }}
{{- end }}
---
{{- end }}
{{- if and .Values.encryption.enabled (not .Values.encryption.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronos-db.fullname" . }}-encryption
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.encryption }}
stringData:
  master.key: {{ .key | default "" | quote }}
{{- end }}
---
{{- end }}
{{- if and .Values.replicationTLS.enabled (not .Values.replicationTLS.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronos-db.fullname" . }}-replication-tls
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.replicationTLS }}
stringData:
  tls.crt: {{ .cert | default "" | quote }}
  tls.key: {{ .key | default "" | quote }}
  ca.crt: {{ .caCert | default "" | quote }}
{{- end }}
{{- end }}
