{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronos-db.fullname" . }}-tls
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.tls }}
stringData:
  tls.crt: {{ .cert | default "" | quote }}
  tls.key: {{ .key | default "" | quote }}
  ca.crt: {{ .caCert | default "" | quote }}
{{- end }}
{{- end }}
