apiVersion: v1
kind: Service
metadata:
  name: {{ include "cronos-db.headlessServiceName" . }}
  labels:
    {{- include "cronos-db.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: gossip
      port: {{ .Values.headlessService.gossipPort }}
      targetPort: gossip
      protocol: TCP
    - name: cluster-grpc
      port: {{ .Values.headlessService.clusterGRPCPort }}
      targetPort: cluster-grpc
      protocol: TCP
    - name: raft
      port: {{ .Values.headlessService.raftPort }}
      targetPort: raft
      protocol: TCP
  selector:
    {{- include "cronos-db.selectorLabels" . | nindent 4 }}
