// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetClusterTopology_FullMethodName  = "/cronos_db_admin.AdminService/GetClusterTopology"
	AdminService_GetPartitionHealth_FullMethodName  = "/cronos_db_admin.AdminService/GetPartitionHealth"
	AdminService_GetReplicationLag_FullMethodName   = "/cronos_db_admin.AdminService/GetReplicationLag"
	AdminService_ListConsumerGroups_FullMethodName  = "/cronos_db_admin.AdminService/ListConsumerGroups"
	AdminService_GetConsumerGroupLag_FullMethodName = "/cronos_db_admin.AdminService/GetConsumerGroupLag"
	AdminService_RunRetention_FullMethodName        = "/cronos_db_admin.AdminService/RunRetention"
	AdminService_RunCompaction_FullMethodName       = "/cronos_db_admin.AdminService/RunCompaction"
	AdminService_ListSchemas_FullMethodName         = "/cronos_db_admin.AdminService/ListSchemas"
	AdminService_GetSchema_FullMethodName           = "/cronos_db_admin.AdminService/GetSchema"
	AdminService_GetTenantUsage_FullMethodName      = "/cronos_db_admin.AdminService/GetTenantUsage"
	AdminService_TriggerRebalance_FullMethodName    = "/cronos_db_admin.AdminService/TriggerRebalance"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// GetClusterTopology returns the responding peer's view of the cluster
	// (nodes + partition assignments + ISR + per-follower offsets).
	GetClusterTopology(ctx context.Context, in *GetClusterTopologyRequest, opts ...grpc.CallOption) (*ClusterTopology, error)
	// GetPartitionHealth returns per-partition runtime stats (WAL, scheduler,
	// dedup, replay status). [stub]
	GetPartitionHealth(ctx context.Context, in *PartitionHealth, opts ...grpc.CallOption) (*PartitionHealthResponse, error)
	// GetReplicationLag returns leader HWM and per-follower lag for one or all
	// partitions. [stub]
	GetReplicationLag(ctx context.Context, in *ReplicationLag, opts ...grpc.CallOption) (*ReplicationLagResponse, error)
	// ListConsumerGroups returns every consumer group known to the cluster.
	// [stub]
	ListConsumerGroups(ctx context.Context, in *AdminListConsumerGroupsRequest, opts ...grpc.CallOption) (*AdminListConsumerGroupsResponse, error)
	// GetConsumerGroupLag returns the committed-vs-high-watermark lag for a
	// single (group, partition). [stub]
	GetConsumerGroupLag(ctx context.Context, in *AdminConsumerGroupLag, opts ...grpc.CallOption) (*AdminConsumerGroupLagResponse, error)
	// RunRetention runs age/size-based retention once. [stub]
	RunRetention(ctx context.Context, in *RunRetentionRequest, opts ...grpc.CallOption) (*RunRetentionResponse, error)
	// RunCompaction runs consumer-offset-bounded compaction once. [stub]
	RunCompaction(ctx context.Context, in *RunCompactionRequest, opts ...grpc.CallOption) (*RunCompactionResponse, error)
	// ListSchemas returns every registered topic schema. [stub]
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// GetSchema returns one schema version (or the latest if version=0). [stub]
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// GetTenantUsage returns in-flight + storage usage for one or all tenants.
	// [stub]
	GetTenantUsage(ctx context.Context, in *TenantUsage, opts ...grpc.CallOption) (*TenantUsageResponse, error)
	// TriggerRebalance forces a router rebalance based on current membership.
	// [stub]
	TriggerRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*RebalanceResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetClusterTopology(ctx context.Context, in *GetClusterTopologyRequest, opts ...grpc.CallOption) (*ClusterTopology, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterTopology)
	err := c.cc.Invoke(ctx, AdminService_GetClusterTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPartitionHealth(ctx context.Context, in *PartitionHealth, opts ...grpc.CallOption) (*PartitionHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionHealthResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPartitionHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetReplicationLag(ctx context.Context, in *ReplicationLag, opts ...grpc.CallOption) (*ReplicationLagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationLagResponse)
	err := c.cc.Invoke(ctx, AdminService_GetReplicationLag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListConsumerGroups(ctx context.Context, in *AdminListConsumerGroupsRequest, opts ...grpc.CallOption) (*AdminListConsumerGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListConsumerGroupsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListConsumerGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetConsumerGroupLag(ctx context.Context, in *AdminConsumerGroupLag, opts ...grpc.CallOption) (*AdminConsumerGroupLagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminConsumerGroupLagResponse)
	err := c.cc.Invoke(ctx, AdminService_GetConsumerGroupLag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RunRetention(ctx context.Context, in *RunRetentionRequest, opts ...grpc.CallOption) (*RunRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRetentionResponse)
	err := c.cc.Invoke(ctx, AdminService_RunRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RunCompaction(ctx context.Context, in *RunCompactionRequest, opts ...grpc.CallOption) (*RunCompactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCompactionResponse)
	err := c.cc.Invoke(ctx, AdminService_RunCompaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, AdminService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, AdminService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetTenantUsage(ctx context.Context, in *TenantUsage, opts ...grpc.CallOption) (*TenantUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantUsageResponse)
	err := c.cc.Invoke(ctx, AdminService_GetTenantUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TriggerRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*RebalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebalanceResponse)
	err := c.cc.Invoke(ctx, AdminService_TriggerRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	// GetClusterTopology returns the responding peer's view of the cluster
	// (nodes + partition assignments + ISR + per-follower offsets).
	GetClusterTopology(context.Context, *GetClusterTopologyRequest) (*ClusterTopology, error)
	// GetPartitionHealth returns per-partition runtime stats (WAL, scheduler,
	// dedup, replay status). [stub]
	GetPartitionHealth(context.Context, *PartitionHealth) (*PartitionHealthResponse, error)
	// GetReplicationLag returns leader HWM and per-follower lag for one or all
	// partitions. [stub]
	GetReplicationLag(context.Context, *ReplicationLag) (*ReplicationLagResponse, error)
	// ListConsumerGroups returns every consumer group known to the cluster.
	// [stub]
	ListConsumerGroups(context.Context, *AdminListConsumerGroupsRequest) (*AdminListConsumerGroupsResponse, error)
	// GetConsumerGroupLag returns the committed-vs-high-watermark lag for a
	// single (group, partition). [stub]
	GetConsumerGroupLag(context.Context, *AdminConsumerGroupLag) (*AdminConsumerGroupLagResponse, error)
	// RunRetention runs age/size-based retention once. [stub]
	RunRetention(context.Context, *RunRetentionRequest) (*RunRetentionResponse, error)
	// RunCompaction runs consumer-offset-bounded compaction once. [stub]
	RunCompaction(context.Context, *RunCompactionRequest) (*RunCompactionResponse, error)
	// ListSchemas returns every registered topic schema. [stub]
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// GetSchema returns one schema version (or the latest if version=0). [stub]
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// GetTenantUsage returns in-flight + storage usage for one or all tenants.
	// [stub]
	GetTenantUsage(context.Context, *TenantUsage) (*TenantUsageResponse, error)
	// TriggerRebalance forces a router rebalance based on current membership.
	// [stub]
	TriggerRebalance(context.Context, *RebalanceRequest) (*RebalanceResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetClusterTopology(context.Context, *GetClusterTopologyRequest) (*ClusterTopology, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterTopology not implemented")
}
func (UnimplementedAdminServiceServer) GetPartitionHealth(context.Context, *PartitionHealth) (*PartitionHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartitionHealth not implemented")
}
func (UnimplementedAdminServiceServer) GetReplicationLag(context.Context, *ReplicationLag) (*ReplicationLagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicationLag not implemented")
}
func (UnimplementedAdminServiceServer) ListConsumerGroups(context.Context, *AdminListConsumerGroupsRequest) (*AdminListConsumerGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumerGroups not implemented")
}
func (UnimplementedAdminServiceServer) GetConsumerGroupLag(context.Context, *AdminConsumerGroupLag) (*AdminConsumerGroupLagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerGroupLag not implemented")
}
func (UnimplementedAdminServiceServer) RunRetention(context.Context, *RunRetentionRequest) (*RunRetentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunRetention not implemented")
}
func (UnimplementedAdminServiceServer) RunCompaction(context.Context, *RunCompactionRequest) (*RunCompactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCompaction not implemented")
}
func (UnimplementedAdminServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedAdminServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedAdminServiceServer) GetTenantUsage(context.Context, *TenantUsage) (*TenantUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantUsage not implemented")
}
func (UnimplementedAdminServiceServer) TriggerRebalance(context.Context, *RebalanceRequest) (*RebalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRebalance not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetClusterTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClusterTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClusterTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClusterTopology(ctx, req.(*GetClusterTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPartitionHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionHealth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPartitionHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPartitionHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPartitionHealth(ctx, req.(*PartitionHealth))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetReplicationLag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationLag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetReplicationLag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetReplicationLag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetReplicationLag(ctx, req.(*ReplicationLag))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListConsumerGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListConsumerGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListConsumerGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListConsumerGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListConsumerGroups(ctx, req.(*AdminListConsumerGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetConsumerGroupLag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminConsumerGroupLag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetConsumerGroupLag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetConsumerGroupLag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetConsumerGroupLag(ctx, req.(*AdminConsumerGroupLag))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RunRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RunRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RunRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RunRetention(ctx, req.(*RunRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RunCompaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCompactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RunCompaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RunCompaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RunCompaction(ctx, req.(*RunCompactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetTenantUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantUsage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetTenantUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetTenantUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetTenantUsage(ctx, req.(*TenantUsage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TriggerRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TriggerRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TriggerRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TriggerRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cronos_db_admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterTopology",
			Handler:    _AdminService_GetClusterTopology_Handler,
		},
		{
			MethodName: "GetPartitionHealth",
			Handler:    _AdminService_GetPartitionHealth_Handler,
		},
		{
			MethodName: "GetReplicationLag",
			Handler:    _AdminService_GetReplicationLag_Handler,
		},
		{
			MethodName: "ListConsumerGroups",
			Handler:    _AdminService_ListConsumerGroups_Handler,
		},
		{
			MethodName: "GetConsumerGroupLag",
			Handler:    _AdminService_GetConsumerGroupLag_Handler,
		},
		{
			MethodName: "RunRetention",
			Handler:    _AdminService_RunRetention_Handler,
		},
		{
			MethodName: "RunCompaction",
			Handler:    _AdminService_RunCompaction_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _AdminService_ListSchemas_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _AdminService_GetSchema_Handler,
		},
		{
			MethodName: "GetTenantUsage",
			Handler:    _AdminService_GetTenantUsage_Handler,
		},
		{
			MethodName: "TriggerRebalance",
			Handler:    _AdminService_TriggerRebalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}
