// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/admin.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One node in the cluster as seen by the responding peer.
type AdminNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	IsLocal       bool                   `protobuf:"varint,3,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	IsAlive       bool                   `protobuf:"varint,4,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Rack          string                 `protobuf:"bytes,6,opt,name=rack,proto3" json:"rack,omitempty"`
	Zone          string                 `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	Region        string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNode) Reset() {
	*x = AdminNode{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNode) ProtoMessage() {}

func (x *AdminNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNode.ProtoReflect.Descriptor instead.
func (*AdminNode) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AdminNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AdminNode) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *AdminNode) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *AdminNode) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AdminNode) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *AdminNode) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *AdminNode) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// One partition as seen by the responding peer.
type AdminPartition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PartitionId         int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LeaderId            string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Replicas            []string               `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Isr                 []string               `protobuf:"bytes,4,rep,name=isr,proto3" json:"isr,omitempty"`
	Epoch               int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LeaderHighWatermark int64                  `protobuf:"varint,6,opt,name=leader_high_watermark,json=leaderHighWatermark,proto3" json:"leader_high_watermark,omitempty"`
	FollowerOffsets     map[string]int64       `protobuf:"bytes,7,rep,name=follower_offsets,json=followerOffsets,proto3" json:"follower_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	InSyncCount         int32                  `protobuf:"varint,8,opt,name=in_sync_count,json=inSyncCount,proto3" json:"in_sync_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminPartition) Reset() {
	*x = AdminPartition{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPartition) ProtoMessage() {}

func (x *AdminPartition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPartition.ProtoReflect.Descriptor instead.
func (*AdminPartition) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminPartition) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AdminPartition) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AdminPartition) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *AdminPartition) GetIsr() []string {
	if x != nil {
		return x.Isr
	}
	return nil
}

func (x *AdminPartition) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AdminPartition) GetLeaderHighWatermark() int64 {
	if x != nil {
		return x.LeaderHighWatermark
	}
	return 0
}

func (x *AdminPartition) GetFollowerOffsets() map[string]int64 {
	if x != nil {
		return x.FollowerOffsets
	}
	return nil
}

func (x *AdminPartition) GetInSyncCount() int32 {
	if x != nil {
		return x.InSyncCount
	}
	return 0
}

// Snapshot of the whole cluster topology from the responding peer's view.
type ClusterTopology struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalNodeId      string                 `protobuf:"bytes,1,opt,name=local_node_id,json=localNodeId,proto3" json:"local_node_id,omitempty"`
	IsClusterMode    bool                   `protobuf:"varint,2,opt,name=is_cluster_mode,json=isClusterMode,proto3" json:"is_cluster_mode,omitempty"`
	TotalNodes       int64                  `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	AliveNodes       int64                  `protobuf:"varint,4,opt,name=alive_nodes,json=aliveNodes,proto3" json:"alive_nodes,omitempty"`
	TotalPartitions  int32                  `protobuf:"varint,5,opt,name=total_partitions,json=totalPartitions,proto3" json:"total_partitions,omitempty"`
	LeaderPartitions int32                  `protobuf:"varint,6,opt,name=leader_partitions,json=leaderPartitions,proto3" json:"leader_partitions,omitempty"`
	Nodes            []*AdminNode           `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Partitions       []*AdminPartition      `protobuf:"bytes,8,rep,name=partitions,proto3" json:"partitions,omitempty"`
	CapturedAtUnixMs int64                  `protobuf:"varint,9,opt,name=captured_at_unix_ms,json=capturedAtUnixMs,proto3" json:"captured_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterTopology) Reset() {
	*x = ClusterTopology{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTopology) ProtoMessage() {}

func (x *ClusterTopology) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTopology.ProtoReflect.Descriptor instead.
func (*ClusterTopology) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterTopology) GetLocalNodeId() string {
	if x != nil {
		return x.LocalNodeId
	}
	return ""
}

func (x *ClusterTopology) GetIsClusterMode() bool {
	if x != nil {
		return x.IsClusterMode
	}
	return false
}

func (x *ClusterTopology) GetTotalNodes() int64 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *ClusterTopology) GetAliveNodes() int64 {
	if x != nil {
		return x.AliveNodes
	}
	return 0
}

func (x *ClusterTopology) GetTotalPartitions() int32 {
	if x != nil {
		return x.TotalPartitions
	}
	return 0
}

func (x *ClusterTopology) GetLeaderPartitions() int32 {
	if x != nil {
		return x.LeaderPartitions
	}
	return 0
}

func (x *ClusterTopology) GetNodes() []*AdminNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterTopology) GetPartitions() []*AdminPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *ClusterTopology) GetCapturedAtUnixMs() int64 {
	if x != nil {
		return x.CapturedAtUnixMs
	}
	return 0
}

type GetClusterTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterTopologyRequest) Reset() {
	*x = GetClusterTopologyRequest{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterTopologyRequest) ProtoMessage() {}

func (x *GetClusterTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetClusterTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

type PartitionHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionHealth) Reset() {
	*x = PartitionHealth{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionHealth) ProtoMessage() {}

func (x *PartitionHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionHealth.ProtoReflect.Descriptor instead.
func (*PartitionHealth) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *PartitionHealth) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type PartitionHealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartitionId      int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	HighWatermark    int64                  `protobuf:"varint,2,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	FirstOffset      int64                  `protobuf:"varint,3,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	SegmentCount     int32                  `protobuf:"varint,4,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	DiskUsageBytes   int64                  `protobuf:"varint,5,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	ActiveTimers     int64                  `protobuf:"varint,6,opt,name=active_timers,json=activeTimers,proto3" json:"active_timers,omitempty"`
	ReadyEvents      int64                  `protobuf:"varint,7,opt,name=ready_events,json=readyEvents,proto3" json:"ready_events,omitempty"`
	ColdStoreEntries int64                  `protobuf:"varint,8,opt,name=cold_store_entries,json=coldStoreEntries,proto3" json:"cold_store_entries,omitempty"`
	ReplayError      bool                   `protobuf:"varint,9,opt,name=replay_error,json=replayError,proto3" json:"replay_error,omitempty"`
	LastError        string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PartitionHealthResponse) Reset() {
	*x = PartitionHealthResponse{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionHealthResponse) ProtoMessage() {}

func (x *PartitionHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionHealthResponse.ProtoReflect.Descriptor instead.
func (*PartitionHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *PartitionHealthResponse) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionHealthResponse) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

func (x *PartitionHealthResponse) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *PartitionHealthResponse) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *PartitionHealthResponse) GetDiskUsageBytes() int64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

func (x *PartitionHealthResponse) GetActiveTimers() int64 {
	if x != nil {
		return x.ActiveTimers
	}
	return 0
}

func (x *PartitionHealthResponse) GetReadyEvents() int64 {
	if x != nil {
		return x.ReadyEvents
	}
	return 0
}

func (x *PartitionHealthResponse) GetColdStoreEntries() int64 {
	if x != nil {
		return x.ColdStoreEntries
	}
	return 0
}

func (x *PartitionHealthResponse) GetReplayError() bool {
	if x != nil {
		return x.ReplayError
	}
	return false
}

func (x *PartitionHealthResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ReplicationLag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // 0 means all partitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationLag) Reset() {
	*x = ReplicationLag{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationLag) ProtoMessage() {}

func (x *ReplicationLag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationLag.ProtoReflect.Descriptor instead.
func (*ReplicationLag) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicationLag) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type ReplicationLagResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PartitionId         int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LeaderHighWatermark int64                  `protobuf:"varint,2,opt,name=leader_high_watermark,json=leaderHighWatermark,proto3" json:"leader_high_watermark,omitempty"`
	Followers           []*FollowerLag         `protobuf:"bytes,3,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReplicationLagResponse) Reset() {
	*x = ReplicationLagResponse{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationLagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationLagResponse) ProtoMessage() {}

func (x *ReplicationLagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationLagResponse.ProtoReflect.Descriptor instead.
func (*ReplicationLagResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicationLagResponse) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ReplicationLagResponse) GetLeaderHighWatermark() int64 {
	if x != nil {
		return x.LeaderHighWatermark
	}
	return 0
}

func (x *ReplicationLagResponse) GetFollowers() []*FollowerLag {
	if x != nil {
		return x.Followers
	}
	return nil
}

type FollowerLag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	LagEvents     int64                  `protobuf:"varint,3,opt,name=lag_events,json=lagEvents,proto3" json:"lag_events,omitempty"`
	LagSeconds    int64                  `protobuf:"varint,4,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	InSync        bool                   `protobuf:"varint,5,opt,name=in_sync,json=inSync,proto3" json:"in_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerLag) Reset() {
	*x = FollowerLag{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerLag) ProtoMessage() {}

func (x *FollowerLag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerLag.ProtoReflect.Descriptor instead.
func (*FollowerLag) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *FollowerLag) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowerLag) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FollowerLag) GetLagEvents() int64 {
	if x != nil {
		return x.LagEvents
	}
	return 0
}

func (x *FollowerLag) GetLagSeconds() int64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

func (x *FollowerLag) GetInSync() bool {
	if x != nil {
		return x.InSync
	}
	return false
}

type AdminConsumerGroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []int32                `protobuf:"varint,3,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	MemberCount   int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminConsumerGroupSummary) Reset() {
	*x = AdminConsumerGroupSummary{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminConsumerGroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminConsumerGroupSummary) ProtoMessage() {}

func (x *AdminConsumerGroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminConsumerGroupSummary.ProtoReflect.Descriptor instead.
func (*AdminConsumerGroupSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminConsumerGroupSummary) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AdminConsumerGroupSummary) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AdminConsumerGroupSummary) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *AdminConsumerGroupSummary) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type AdminListConsumerGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListConsumerGroupsRequest) Reset() {
	*x = AdminListConsumerGroupsRequest{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListConsumerGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListConsumerGroupsRequest) ProtoMessage() {}

func (x *AdminListConsumerGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListConsumerGroupsRequest.ProtoReflect.Descriptor instead.
func (*AdminListConsumerGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

type AdminListConsumerGroupsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Groups        []*AdminConsumerGroupSummary `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListConsumerGroupsResponse) Reset() {
	*x = AdminListConsumerGroupsResponse{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListConsumerGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListConsumerGroupsResponse) ProtoMessage() {}

func (x *AdminListConsumerGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListConsumerGroupsResponse.ProtoReflect.Descriptor instead.
func (*AdminListConsumerGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminListConsumerGroupsResponse) GetGroups() []*AdminConsumerGroupSummary {
	if x != nil {
		return x.Groups
	}
	return nil
}

type AdminConsumerGroupLag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminConsumerGroupLag) Reset() {
	*x = AdminConsumerGroupLag{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminConsumerGroupLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminConsumerGroupLag) ProtoMessage() {}

func (x *AdminConsumerGroupLag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminConsumerGroupLag.ProtoReflect.Descriptor instead.
func (*AdminConsumerGroupLag) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminConsumerGroupLag) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AdminConsumerGroupLag) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type AdminConsumerGroupLagResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GroupId                string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PartitionId            int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	CommittedOffset        int64                  `protobuf:"varint,3,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	PartitionHighWatermark int64                  `protobuf:"varint,4,opt,name=partition_high_watermark,json=partitionHighWatermark,proto3" json:"partition_high_watermark,omitempty"`
	Lag                    int64                  `protobuf:"varint,5,opt,name=lag,proto3" json:"lag,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminConsumerGroupLagResponse) Reset() {
	*x = AdminConsumerGroupLagResponse{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminConsumerGroupLagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminConsumerGroupLagResponse) ProtoMessage() {}

func (x *AdminConsumerGroupLagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminConsumerGroupLagResponse.ProtoReflect.Descriptor instead.
func (*AdminConsumerGroupLagResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminConsumerGroupLagResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AdminConsumerGroupLagResponse) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AdminConsumerGroupLagResponse) GetCommittedOffset() int64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

func (x *AdminConsumerGroupLagResponse) GetPartitionHighWatermark() int64 {
	if x != nil {
		return x.PartitionHighWatermark
	}
	return 0
}

func (x *AdminConsumerGroupLagResponse) GetLag() int64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

type RunRetentionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // 0 means all partitions
	MaxAgeHours   int64                  `protobuf:"varint,2,opt,name=max_age_hours,json=maxAgeHours,proto3" json:"max_age_hours,omitempty"`
	MaxSizeBytes  int64                  `protobuf:"varint,3,opt,name=max_size_bytes,json=maxSizeBytes,proto3" json:"max_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRetentionRequest) Reset() {
	*x = RunRetentionRequest{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRetentionRequest) ProtoMessage() {}

func (x *RunRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRetentionRequest.ProtoReflect.Descriptor instead.
func (*RunRetentionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RunRetentionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *RunRetentionRequest) GetMaxAgeHours() int64 {
	if x != nil {
		return x.MaxAgeHours
	}
	return 0
}

func (x *RunRetentionRequest) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.MaxSizeBytes
	}
	return 0
}

type RunRetentionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SegmentsDeleted int64                  `protobuf:"varint,3,opt,name=segments_deleted,json=segmentsDeleted,proto3" json:"segments_deleted,omitempty"`
	BytesFreed      int64                  `protobuf:"varint,4,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunRetentionResponse) Reset() {
	*x = RunRetentionResponse{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRetentionResponse) ProtoMessage() {}

func (x *RunRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRetentionResponse.ProtoReflect.Descriptor instead.
func (*RunRetentionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RunRetentionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunRetentionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunRetentionResponse) GetSegmentsDeleted() int64 {
	if x != nil {
		return x.SegmentsDeleted
	}
	return 0
}

func (x *RunRetentionResponse) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

type RunCompactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // 0 means all partitions
	BeforeOffset  int64                  `protobuf:"varint,2,opt,name=before_offset,json=beforeOffset,proto3" json:"before_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCompactionRequest) Reset() {
	*x = RunCompactionRequest{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompactionRequest) ProtoMessage() {}

func (x *RunCompactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompactionRequest.ProtoReflect.Descriptor instead.
func (*RunCompactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RunCompactionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *RunCompactionRequest) GetBeforeOffset() int64 {
	if x != nil {
		return x.BeforeOffset
	}
	return 0
}

type RunCompactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SegmentsCompacted int64                  `protobuf:"varint,3,opt,name=segments_compacted,json=segmentsCompacted,proto3" json:"segments_compacted,omitempty"`
	BytesReclaimed    int64                  `protobuf:"varint,4,opt,name=bytes_reclaimed,json=bytesReclaimed,proto3" json:"bytes_reclaimed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunCompactionResponse) Reset() {
	*x = RunCompactionResponse{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompactionResponse) ProtoMessage() {}

func (x *RunCompactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompactionResponse.ProtoReflect.Descriptor instead.
func (*RunCompactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RunCompactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunCompactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunCompactionResponse) GetSegmentsCompacted() int64 {
	if x != nil {
		return x.SegmentsCompacted
	}
	return 0
}

func (x *RunCompactionResponse) GetBytesReclaimed() int64 {
	if x != nil {
		return x.BytesReclaimed
	}
	return 0
}

type SchemaSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	LatestVersion     int32                  `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	CompatibilityMode string                 `protobuf:"bytes,3,opt,name=compatibility_mode,json=compatibilityMode,proto3" json:"compatibility_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchemaSummary) Reset() {
	*x = SchemaSummary{}
	mi := &file_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaSummary) ProtoMessage() {}

func (x *SchemaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaSummary.ProtoReflect.Descriptor instead.
func (*SchemaSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *SchemaSummary) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SchemaSummary) GetLatestVersion() int32 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *SchemaSummary) GetCompatibilityMode() string {
	if x != nil {
		return x.CompatibilityMode
	}
	return ""
}

type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{19}
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*SchemaSummary       `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaSummary {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 0 means latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *GetSchemaRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetSchemaRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	SchemaType    string                 `protobuf:"bytes,3,opt,name=schema_type,json=schemaType,proto3" json:"schema_type,omitempty"`
	Definition    string                 `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetSchemaResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetSchemaResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSchemaResponse) GetSchemaType() string {
	if x != nil {
		return x.SchemaType
	}
	return ""
}

func (x *GetSchemaResponse) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type TenantUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // empty means all tenants
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUsage) Reset() {
	*x = TenantUsage{}
	mi := &file_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUsage) ProtoMessage() {}

func (x *TenantUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUsage.ProtoReflect.Descriptor instead.
func (*TenantUsage) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *TenantUsage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantUsageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InFlight          int64                  `protobuf:"varint,2,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	StorageBytes      int64                  `protobuf:"varint,3,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	LimitsConfigured  bool                   `protobuf:"varint,4,opt,name=limits_configured,json=limitsConfigured,proto3" json:"limits_configured,omitempty"`
	PublishRatePerSec int64                  `protobuf:"varint,5,opt,name=publish_rate_per_sec,json=publishRatePerSec,proto3" json:"publish_rate_per_sec,omitempty"`
	MaxInFlight       int64                  `protobuf:"varint,6,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TenantUsageResponse) Reset() {
	*x = TenantUsageResponse{}
	mi := &file_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUsageResponse) ProtoMessage() {}

func (x *TenantUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUsageResponse.ProtoReflect.Descriptor instead.
func (*TenantUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *TenantUsageResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantUsageResponse) GetInFlight() int64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *TenantUsageResponse) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *TenantUsageResponse) GetLimitsConfigured() bool {
	if x != nil {
		return x.LimitsConfigured
	}
	return false
}

func (x *TenantUsageResponse) GetPublishRatePerSec() int64 {
	if x != nil {
		return x.PublishRatePerSec
	}
	return 0
}

func (x *TenantUsageResponse) GetMaxInFlight() int64 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

type RebalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceRequest) Reset() {
	*x = RebalanceRequest{}
	mi := &file_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRequest) ProtoMessage() {}

func (x *RebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRequest.ProtoReflect.Descriptor instead.
func (*RebalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{25}
}

type RebalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PartitionsMoved int32                  `protobuf:"varint,3,opt,name=partitions_moved,json=partitionsMoved,proto3" json:"partitions_moved,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RebalanceResponse) Reset() {
	*x = RebalanceResponse{}
	mi := &file_proto_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceResponse) ProtoMessage() {}

func (x *RebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceResponse.ProtoReflect.Descriptor instead.
func (*RebalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{26}
}

func (x *RebalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebalanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RebalanceResponse) GetPartitionsMoved() int32 {
	if x != nil {
		return x.PartitionsMoved
	}
	return 0
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x0fcronos_db_admin\"\xca\x01\n" +
	"\tAdminNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bis_local\x18\x03 \x01(\bR\aisLocal\x12\x19\n" +
	"\bis_alive\x18\x04 \x01(\bR\aisAlive\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x12\n" +
	"\x04rack\x18\x06 \x01(\tR\x04rack\x12\x12\n" +
	"\x04zone\x18\a \x01(\tR\x04zone\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\"\x91\x03\n" +
	"\x0eAdminPartition\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\tR\breplicas\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\tR\x03isr\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epoch\x122\n" +
	"\x15leader_high_watermark\x18\x06 \x01(\x03R\x13leaderHighWatermark\x12_\n" +
	"\x10follower_offsets\x18\a \x03(\v24.cronos_db_admin.AdminPartition.FollowerOffsetsEntryR\x0ffollowerOffsets\x12\"\n" +
	"\rin_sync_count\x18\b \x01(\x05R\vinSyncCount\x1aB\n" +
	"\x14FollowerOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x99\x03\n" +
	"\x0fClusterTopology\x12\"\n" +
	"\rlocal_node_id\x18\x01 \x01(\tR\vlocalNodeId\x12&\n" +
	"\x0fis_cluster_mode\x18\x02 \x01(\bR\risClusterMode\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x03R\n" +
	"totalNodes\x12\x1f\n" +
	"\valive_nodes\x18\x04 \x01(\x03R\n" +
	"aliveNodes\x12)\n" +
	"\x10total_partitions\x18\x05 \x01(\x05R\x0ftotalPartitions\x12+\n" +
	"\x11leader_partitions\x18\x06 \x01(\x05R\x10leaderPartitions\x120\n" +
	"\x05nodes\x18\a \x03(\v2\x1a.cronos_db_admin.AdminNodeR\x05nodes\x12?\n" +
	"\n" +
	"partitions\x18\b \x03(\v2\x1f.cronos_db_admin.AdminPartitionR\n" +
	"partitions\x12-\n" +
	"\x13captured_at_unix_ms\x18\t \x01(\x03R\x10capturedAtUnixMs\"\x1b\n" +
	"\x19GetClusterTopologyRequest\"4\n" +
	"\x0fPartitionHealth\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\"\x8d\x03\n" +
	"\x17PartitionHealthResponse\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12%\n" +
	"\x0ehigh_watermark\x18\x02 \x01(\x03R\rhighWatermark\x12!\n" +
	"\ffirst_offset\x18\x03 \x01(\x03R\vfirstOffset\x12#\n" +
	"\rsegment_count\x18\x04 \x01(\x05R\fsegmentCount\x12(\n" +
	"\x10disk_usage_bytes\x18\x05 \x01(\x03R\x0ediskUsageBytes\x12#\n" +
	"\ractive_timers\x18\x06 \x01(\x03R\factiveTimers\x12!\n" +
	"\fready_events\x18\a \x01(\x03R\vreadyEvents\x12,\n" +
	"\x12cold_store_entries\x18\b \x01(\x03R\x10coldStoreEntries\x12!\n" +
	"\freplay_error\x18\t \x01(\bR\vreplayError\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\"3\n" +
	"\x0eReplicationLag\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\"\xab\x01\n" +
	"\x16ReplicationLagResponse\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x122\n" +
	"\x15leader_high_watermark\x18\x02 \x01(\x03R\x13leaderHighWatermark\x12:\n" +
	"\tfollowers\x18\x03 \x03(\v2\x1c.cronos_db_admin.FollowerLagR\tfollowers\"\x9f\x01\n" +
	"\vFollowerLag\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"lag_events\x18\x03 \x01(\x03R\tlagEvents\x12\x1f\n" +
	"\vlag_seconds\x18\x04 \x01(\x03R\n" +
	"lagSeconds\x12\x17\n" +
	"\ain_sync\x18\x05 \x01(\bR\x06inSync\"\x8f\x01\n" +
	"\x19AdminConsumerGroupSummary\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x03(\x05R\n" +
	"partitions\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\" \n" +
	"\x1eAdminListConsumerGroupsRequest\"e\n" +
	"\x1fAdminListConsumerGroupsResponse\x12B\n" +
	"\x06groups\x18\x01 \x03(\v2*.cronos_db_admin.AdminConsumerGroupSummaryR\x06groups\"U\n" +
	"\x15AdminConsumerGroupLag\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\"\xd4\x01\n" +
	"\x1dAdminConsumerGroupLagResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12)\n" +
	"\x10committed_offset\x18\x03 \x01(\x03R\x0fcommittedOffset\x128\n" +
	"\x18partition_high_watermark\x18\x04 \x01(\x03R\x16partitionHighWatermark\x12\x10\n" +
	"\x03lag\x18\x05 \x01(\x03R\x03lag\"\x82\x01\n" +
	"\x13RunRetentionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\"\n" +
	"\rmax_age_hours\x18\x02 \x01(\x03R\vmaxAgeHours\x12$\n" +
	"\x0emax_size_bytes\x18\x03 \x01(\x03R\fmaxSizeBytes\"\x92\x01\n" +
	"\x14RunRetentionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x10segments_deleted\x18\x03 \x01(\x03R\x0fsegmentsDeleted\x12\x1f\n" +
	"\vbytes_freed\x18\x04 \x01(\x03R\n" +
	"bytesFreed\"^\n" +
	"\x14RunCompactionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\rbefore_offset\x18\x02 \x01(\x03R\fbeforeOffset\"\x9f\x01\n" +
	"\x15RunCompactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x12segments_compacted\x18\x03 \x01(\x03R\x11segmentsCompacted\x12'\n" +
	"\x0fbytes_reclaimed\x18\x04 \x01(\x03R\x0ebytesReclaimed\"{\n" +
	"\rSchemaSummary\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\x05R\rlatestVersion\x12-\n" +
	"\x12compatibility_mode\x18\x03 \x01(\tR\x11compatibilityMode\"\x14\n" +
	"\x12ListSchemasRequest\"O\n" +
	"\x13ListSchemasResponse\x128\n" +
	"\aschemas\x18\x01 \x03(\v2\x1e.cronos_db_admin.SchemaSummaryR\aschemas\"B\n" +
	"\x10GetSchemaRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\x84\x01\n" +
	"\x11GetSchemaResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1f\n" +
	"\vschema_type\x18\x03 \x01(\tR\n" +
	"schemaType\x12\x1e\n" +
	"\n" +
	"definition\x18\x04 \x01(\tR\n" +
	"definition\"*\n" +
	"\vTenantUsage\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xf6\x01\n" +
	"\x13TenantUsageResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tin_flight\x18\x02 \x01(\x03R\binFlight\x12#\n" +
	"\rstorage_bytes\x18\x03 \x01(\x03R\fstorageBytes\x12+\n" +
	"\x11limits_configured\x18\x04 \x01(\bR\x10limitsConfigured\x12/\n" +
	"\x14publish_rate_per_sec\x18\x05 \x01(\x03R\x11publishRatePerSec\x12\"\n" +
	"\rmax_in_flight\x18\x06 \x01(\x03R\vmaxInFlight\"\x12\n" +
	"\x10RebalanceRequest\"n\n" +
	"\x11RebalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x10partitions_moved\x18\x03 \x01(\x05R\x0fpartitionsMoved2\xb7\b\n" +
	"\fAdminService\x12b\n" +
	"\x12GetClusterTopology\x12*.cronos_db_admin.GetClusterTopologyRequest\x1a .cronos_db_admin.ClusterTopology\x12`\n" +
	"\x12GetPartitionHealth\x12 .cronos_db_admin.PartitionHealth\x1a(.cronos_db_admin.PartitionHealthResponse\x12]\n" +
	"\x11GetReplicationLag\x12\x1f.cronos_db_admin.ReplicationLag\x1a'.cronos_db_admin.ReplicationLagResponse\x12w\n" +
	"\x12ListConsumerGroups\x12/.cronos_db_admin.AdminListConsumerGroupsRequest\x1a0.cronos_db_admin.AdminListConsumerGroupsResponse\x12m\n" +
	"\x13GetConsumerGroupLag\x12&.cronos_db_admin.AdminConsumerGroupLag\x1a..cronos_db_admin.AdminConsumerGroupLagResponse\x12[\n" +
	"\fRunRetention\x12$.cronos_db_admin.RunRetentionRequest\x1a%.cronos_db_admin.RunRetentionResponse\x12^\n" +
	"\rRunCompaction\x12%.cronos_db_admin.RunCompactionRequest\x1a&.cronos_db_admin.RunCompactionResponse\x12X\n" +
	"\vListSchemas\x12#.cronos_db_admin.ListSchemasRequest\x1a$.cronos_db_admin.ListSchemasResponse\x12R\n" +
	"\tGetSchema\x12!.cronos_db_admin.GetSchemaRequest\x1a\".cronos_db_admin.GetSchemaResponse\x12T\n" +
	"\x0eGetTenantUsage\x12\x1c.cronos_db_admin.TenantUsage\x1a$.cronos_db_admin.TenantUsageResponse\x12Y\n" +
	"\x10TriggerRebalance\x12!.cronos_db_admin.RebalanceRequest\x1a\".cronos_db_admin.RebalanceResponseB<Z:github.com/jatin711-debug/cronos_db_golang/pkg/types;typesb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_admin_proto_goTypes = []any{
	(*AdminNode)(nil),                       // 0: cronos_db_admin.AdminNode
	(*AdminPartition)(nil),                  // 1: cronos_db_admin.AdminPartition
	(*ClusterTopology)(nil),                 // 2: cronos_db_admin.ClusterTopology
	(*GetClusterTopologyRequest)(nil),       // 3: cronos_db_admin.GetClusterTopologyRequest
	(*PartitionHealth)(nil),                 // 4: cronos_db_admin.PartitionHealth
	(*PartitionHealthResponse)(nil),         // 5: cronos_db_admin.PartitionHealthResponse
	(*ReplicationLag)(nil),                  // 6: cronos_db_admin.ReplicationLag
	(*ReplicationLagResponse)(nil),          // 7: cronos_db_admin.ReplicationLagResponse
	(*FollowerLag)(nil),                     // 8: cronos_db_admin.FollowerLag
	(*AdminConsumerGroupSummary)(nil),       // 9: cronos_db_admin.AdminConsumerGroupSummary
	(*AdminListConsumerGroupsRequest)(nil),  // 10: cronos_db_admin.AdminListConsumerGroupsRequest
	(*AdminListConsumerGroupsResponse)(nil), // 11: cronos_db_admin.AdminListConsumerGroupsResponse
	(*AdminConsumerGroupLag)(nil),           // 12: cronos_db_admin.AdminConsumerGroupLag
	(*AdminConsumerGroupLagResponse)(nil),   // 13: cronos_db_admin.AdminConsumerGroupLagResponse
	(*RunRetentionRequest)(nil),             // 14: cronos_db_admin.RunRetentionRequest
	(*RunRetentionResponse)(nil),            // 15: cronos_db_admin.RunRetentionResponse
	(*RunCompactionRequest)(nil),            // 16: cronos_db_admin.RunCompactionRequest
	(*RunCompactionResponse)(nil),           // 17: cronos_db_admin.RunCompactionResponse
	(*SchemaSummary)(nil),                   // 18: cronos_db_admin.SchemaSummary
	(*ListSchemasRequest)(nil),              // 19: cronos_db_admin.ListSchemasRequest
	(*ListSchemasResponse)(nil),             // 20: cronos_db_admin.ListSchemasResponse
	(*GetSchemaRequest)(nil),                // 21: cronos_db_admin.GetSchemaRequest
	(*GetSchemaResponse)(nil),               // 22: cronos_db_admin.GetSchemaResponse
	(*TenantUsage)(nil),                     // 23: cronos_db_admin.TenantUsage
	(*TenantUsageResponse)(nil),             // 24: cronos_db_admin.TenantUsageResponse
	(*RebalanceRequest)(nil),                // 25: cronos_db_admin.RebalanceRequest
	(*RebalanceResponse)(nil),               // 26: cronos_db_admin.RebalanceResponse
	nil,                                     // 27: cronos_db_admin.AdminPartition.FollowerOffsetsEntry
}
var file_proto_admin_proto_depIdxs = []int32{
	27, // 0: cronos_db_admin.AdminPartition.follower_offsets:type_name -> cronos_db_admin.AdminPartition.FollowerOffsetsEntry
	0,  // 1: cronos_db_admin.ClusterTopology.nodes:type_name -> cronos_db_admin.AdminNode
	1,  // 2: cronos_db_admin.ClusterTopology.partitions:type_name -> cronos_db_admin.AdminPartition
	8,  // 3: cronos_db_admin.ReplicationLagResponse.followers:type_name -> cronos_db_admin.FollowerLag
	9,  // 4: cronos_db_admin.AdminListConsumerGroupsResponse.groups:type_name -> cronos_db_admin.AdminConsumerGroupSummary
	18, // 5: cronos_db_admin.ListSchemasResponse.schemas:type_name -> cronos_db_admin.SchemaSummary
	3,  // 6: cronos_db_admin.AdminService.GetClusterTopology:input_type -> cronos_db_admin.GetClusterTopologyRequest
	4,  // 7: cronos_db_admin.AdminService.GetPartitionHealth:input_type -> cronos_db_admin.PartitionHealth
	6,  // 8: cronos_db_admin.AdminService.GetReplicationLag:input_type -> cronos_db_admin.ReplicationLag
	10, // 9: cronos_db_admin.AdminService.ListConsumerGroups:input_type -> cronos_db_admin.AdminListConsumerGroupsRequest
	12, // 10: cronos_db_admin.AdminService.GetConsumerGroupLag:input_type -> cronos_db_admin.AdminConsumerGroupLag
	14, // 11: cronos_db_admin.AdminService.RunRetention:input_type -> cronos_db_admin.RunRetentionRequest
	16, // 12: cronos_db_admin.AdminService.RunCompaction:input_type -> cronos_db_admin.RunCompactionRequest
	19, // 13: cronos_db_admin.AdminService.ListSchemas:input_type -> cronos_db_admin.ListSchemasRequest
	21, // 14: cronos_db_admin.AdminService.GetSchema:input_type -> cronos_db_admin.GetSchemaRequest
	23, // 15: cronos_db_admin.AdminService.GetTenantUsage:input_type -> cronos_db_admin.TenantUsage
	25, // 16: cronos_db_admin.AdminService.TriggerRebalance:input_type -> cronos_db_admin.RebalanceRequest
	2,  // 17: cronos_db_admin.AdminService.GetClusterTopology:output_type -> cronos_db_admin.ClusterTopology
	5,  // 18: cronos_db_admin.AdminService.GetPartitionHealth:output_type -> cronos_db_admin.PartitionHealthResponse
	7,  // 19: cronos_db_admin.AdminService.GetReplicationLag:output_type -> cronos_db_admin.ReplicationLagResponse
	11, // 20: cronos_db_admin.AdminService.ListConsumerGroups:output_type -> cronos_db_admin.AdminListConsumerGroupsResponse
	13, // 21: cronos_db_admin.AdminService.GetConsumerGroupLag:output_type -> cronos_db_admin.AdminConsumerGroupLagResponse
	15, // 22: cronos_db_admin.AdminService.RunRetention:output_type -> cronos_db_admin.RunRetentionResponse
	17, // 23: cronos_db_admin.AdminService.RunCompaction:output_type -> cronos_db_admin.RunCompactionResponse
	20, // 24: cronos_db_admin.AdminService.ListSchemas:output_type -> cronos_db_admin.ListSchemasResponse
	22, // 25: cronos_db_admin.AdminService.GetSchema:output_type -> cronos_db_admin.GetSchemaResponse
	24, // 26: cronos_db_admin.AdminService.GetTenantUsage:output_type -> cronos_db_admin.TenantUsageResponse
	26, // 27: cronos_db_admin.AdminService.TriggerRebalance:output_type -> cronos_db_admin.RebalanceResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
