// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/events.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier for deduplication
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Timestamp when event should be triggered (Unix epoch in milliseconds)
	ScheduleTs int64 `protobuf:"varint,2,opt,name=schedule_ts,json=scheduleTs,proto3" json:"schedule_ts,omitempty"`
	// Event payload (arbitrary data)
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Topic or channel name
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// Metadata key-value pairs
	Meta map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp (set by server)
	CreatedTs int64 `protobuf:"varint,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	// Event offset within the partition
	Offset int64 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	// Partition ID
	PartitionId int32 `protobuf:"varint,8,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Optional checksum for payload integrity
	Checksum      uint32 `protobuf:"varint,9,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetScheduleTs() int64 {
	if x != nil {
		return x.ScheduleTs
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Event) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Event) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *Event) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Event) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *Event) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// If true, allow duplicate message_id (for testing)
	AllowDuplicate bool `protobuf:"varint,2,opt,name=allow_duplicate,json=allowDuplicate,proto3" json:"allow_duplicate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PublishRequest) GetAllowDuplicate() bool {
	if x != nil {
		return x.AllowDuplicate
	}
	return false
}

type PublishResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Persistent offset assigned to the event
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Partition where event was stored
	PartitionId int32 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Actual schedule timestamp (may be adjusted by server)
	ScheduleTs    int64 `protobuf:"varint,5,opt,name=schedule_ts,json=scheduleTs,proto3" json:"schedule_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishResponse) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PublishResponse) GetScheduleTs() int64 {
	if x != nil {
		return x.ScheduleTs
	}
	return 0
}

// Batch publish request for high-throughput ingestion
type PublishBatchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// If true, allow duplicate message_ids (for testing)
	AllowDuplicate bool `protobuf:"varint,2,opt,name=allow_duplicate,json=allowDuplicate,proto3" json:"allow_duplicate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PublishBatchRequest) GetAllowDuplicate() bool {
	if x != nil {
		return x.AllowDuplicate
	}
	return false
}

// Batch publish response
type PublishBatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PublishedCount int32                  `protobuf:"varint,3,opt,name=published_count,json=publishedCount,proto3" json:"published_count,omitempty"`
	DuplicateCount int32                  `protobuf:"varint,4,opt,name=duplicate_count,json=duplicateCount,proto3" json:"duplicate_count,omitempty"`
	ErrorCount     int32                  `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// First offset in the batch
	FirstOffset int64 `protobuf:"varint,6,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	// Last offset in the batch
	LastOffset    int64 `protobuf:"varint,7,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *PublishBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishBatchResponse) GetPublishedCount() int32 {
	if x != nil {
		return x.PublishedCount
	}
	return 0
}

func (x *PublishBatchResponse) GetDuplicateCount() int32 {
	if x != nil {
		return x.DuplicateCount
	}
	return 0
}

func (x *PublishBatchResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *PublishBatchResponse) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *PublishBatchResponse) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consumer group ID
	ConsumerGroup string `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Topic to subscribe to
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// Partition ID (optional, if -1 auto-assign)
	PartitionId int32 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Offset to start from (if -1, start from latest)
	StartOffset int64 `protobuf:"varint,4,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// Maximum number of events to buffer
	MaxBufferSize int32 `protobuf:"varint,5,opt,name=max_buffer_size,json=maxBufferSize,proto3" json:"max_buffer_size,omitempty"`
	// Subscription ID (for tracking)
	SubscriptionId string `protobuf:"bytes,6,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Whether to replay historical events or only new ones
	Replay        bool `protobuf:"varint,7,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *SubscribeRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SubscribeRequest) GetMaxBufferSize() int32 {
	if x != nil {
		return x.MaxBufferSize
	}
	return 0
}

func (x *SubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscribeRequest) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type Delivery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Delivery ID for tracking
	DeliveryId string `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// Delivery attempt number
	Attempt int32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Timeout for ack (milliseconds)
	AckTimeoutMs int32 `protobuf:"varint,4,opt,name=ack_timeout_ms,json=ackTimeoutMs,proto3" json:"ack_timeout_ms,omitempty"`
	// Batch of events (for batched delivery optimization)
	Batch         []*Event `protobuf:"bytes,5,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *Delivery) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Delivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Delivery) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Delivery) GetAckTimeoutMs() int32 {
	if x != nil {
		return x.AckTimeoutMs
	}
	return 0
}

func (x *Delivery) GetBatch() []*Event {
	if x != nil {
		return x.Batch
	}
	return nil
}

type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delivery ID from Delivery message
	DeliveryId string `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// Whether the event was successfully processed
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Optional error message if processing failed
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Next offset to commit (optional, server can compute)
	NextOffset    int64 `protobuf:"varint,5,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *AckRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AckRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AckRequest) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

type AckResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Committed offset for this consumer group
	CommittedOffset int64 `protobuf:"varint,3,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AckResponse) GetCommittedOffset() int64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

type ReplayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic to replay
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Partition ID (optional, replay all partitions if not specified)
	PartitionId int32 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Start timestamp (Unix ms, optional if using offset)
	StartTs int64 `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	// End timestamp (Unix ms, optional)
	EndTs int64 `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	// Start offset (alternative to start_ts)
	StartOffset int64 `protobuf:"varint,5,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// Number of events to replay (optional)
	Count int64 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	// Consumer group to replay for
	ConsumerGroup string `protobuf:"bytes,7,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Subscription ID for tracking
	SubscriptionId string `protobuf:"bytes,8,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Replay speed: 0=fast, 1=real-time
	Speed         float64 `protobuf:"fixed64,9,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *ReplayRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReplayRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ReplayRequest) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *ReplayRequest) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *ReplayRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ReplayRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReplayRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ReplayRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ReplayRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ReplayEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	ReplayOffset  int64                  `protobuf:"varint,2,opt,name=replay_offset,json=replayOffset,proto3" json:"replay_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayEvent) Reset() {
	*x = ReplayEvent{}
	mi := &file_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayEvent) ProtoMessage() {}

func (x *ReplayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayEvent.ProtoReflect.Descriptor instead.
func (*ReplayEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ReplayEvent) GetReplayOffset() int64 {
	if x != nil {
		return x.ReplayOffset
	}
	return 0
}

type ConsumerGroupMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic            string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions       []int32                `protobuf:"varint,3,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	CommittedOffsets map[int32]int64        `protobuf:"bytes,4,rep,name=committed_offsets,json=committedOffsets,proto3" json:"committed_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MemberOffsets    map[string]int64       `protobuf:"bytes,5,rep,name=member_offsets,json=memberOffsets,proto3" json:"member_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastRebalanceTs  int64                  `protobuf:"varint,6,opt,name=last_rebalance_ts,json=lastRebalanceTs,proto3" json:"last_rebalance_ts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsumerGroupMetadata) Reset() {
	*x = ConsumerGroupMetadata{}
	mi := &file_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerGroupMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerGroupMetadata) ProtoMessage() {}

func (x *ConsumerGroupMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerGroupMetadata.ProtoReflect.Descriptor instead.
func (*ConsumerGroupMetadata) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *ConsumerGroupMetadata) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ConsumerGroupMetadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumerGroupMetadata) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *ConsumerGroupMetadata) GetCommittedOffsets() map[int32]int64 {
	if x != nil {
		return x.CommittedOffsets
	}
	return nil
}

func (x *ConsumerGroupMetadata) GetMemberOffsets() map[string]int64 {
	if x != nil {
		return x.MemberOffsets
	}
	return nil
}

func (x *ConsumerGroupMetadata) GetLastRebalanceTs() int64 {
	if x != nil {
		return x.LastRebalanceTs
	}
	return 0
}

type CreateConsumerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []int32                `protobuf:"varint,3,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsumerGroupRequest) Reset() {
	*x = CreateConsumerGroupRequest{}
	mi := &file_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsumerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerGroupRequest) ProtoMessage() {}

func (x *CreateConsumerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateConsumerGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *CreateConsumerGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateConsumerGroupRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateConsumerGroupRequest) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type CreateConsumerGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsumerGroupResponse) Reset() {
	*x = CreateConsumerGroupResponse{}
	mi := &file_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsumerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerGroupResponse) ProtoMessage() {}

func (x *CreateConsumerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateConsumerGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *CreateConsumerGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateConsumerGroupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetConsumerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsumerGroupRequest) Reset() {
	*x = GetConsumerGroupRequest{}
	mi := &file_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsumerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerGroupRequest) ProtoMessage() {}

func (x *GetConsumerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerGroupRequest.ProtoReflect.Descriptor instead.
func (*GetConsumerGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *GetConsumerGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListConsumerGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // optional, list all if not specified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumerGroupsRequest) Reset() {
	*x = ListConsumerGroupsRequest{}
	mi := &file_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumerGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerGroupsRequest) ProtoMessage() {}

func (x *ListConsumerGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListConsumerGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *ListConsumerGroupsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListConsumerGroupsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Groups        []*ConsumerGroupMetadata `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumerGroupsResponse) Reset() {
	*x = ListConsumerGroupsResponse{}
	mi := &file_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumerGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerGroupsResponse) ProtoMessage() {}

func (x *ListConsumerGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListConsumerGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *ListConsumerGroupsResponse) GetGroups() []*ConsumerGroupMetadata {
	if x != nil {
		return x.Groups
	}
	return nil
}

type RebalanceConsumerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceConsumerGroupRequest) Reset() {
	*x = RebalanceConsumerGroupRequest{}
	mi := &file_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceConsumerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceConsumerGroupRequest) ProtoMessage() {}

func (x *RebalanceConsumerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceConsumerGroupRequest.ProtoReflect.Descriptor instead.
func (*RebalanceConsumerGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *RebalanceConsumerGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RebalanceConsumerGroupRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type RebalanceConsumerGroupResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PartitionAssignments map[string]int32       `protobuf:"bytes,3,rep,name=partition_assignments,json=partitionAssignments,proto3" json:"partition_assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RebalanceConsumerGroupResponse) Reset() {
	*x = RebalanceConsumerGroupResponse{}
	mi := &file_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceConsumerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceConsumerGroupResponse) ProtoMessage() {}

func (x *RebalanceConsumerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceConsumerGroupResponse.ProtoReflect.Descriptor instead.
func (*RebalanceConsumerGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *RebalanceConsumerGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebalanceConsumerGroupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RebalanceConsumerGroupResponse) GetPartitionAssignments() map[string]int32 {
	if x != nil {
		return x.PartitionAssignments
	}
	return nil
}

type ReplicationAppendRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Batch of events to append
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Expected next offset (for gap detection)
	ExpectedNextOffset int64 `protobuf:"varint,3,opt,name=expected_next_offset,json=expectedNextOffset,proto3" json:"expected_next_offset,omitempty"`
	// Leader term
	Term          int64 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationAppendRequest) Reset() {
	*x = ReplicationAppendRequest{}
	mi := &file_proto_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationAppendRequest) ProtoMessage() {}

func (x *ReplicationAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationAppendRequest.ProtoReflect.Descriptor instead.
func (*ReplicationAppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{19}
}

func (x *ReplicationAppendRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ReplicationAppendRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReplicationAppendRequest) GetExpectedNextOffset() int64 {
	if x != nil {
		return x.ExpectedNextOffset
	}
	return 0
}

func (x *ReplicationAppendRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ReplicationAppendResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Last replicated offset
	LastOffset int64 `protobuf:"varint,3,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	// Next expected offset
	NextOffset    int64 `protobuf:"varint,4,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationAppendResponse) Reset() {
	*x = ReplicationAppendResponse{}
	mi := &file_proto_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationAppendResponse) ProtoMessage() {}

func (x *ReplicationAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationAppendResponse.ProtoReflect.Descriptor instead.
func (*ReplicationAppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{20}
}

func (x *ReplicationAppendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationAppendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReplicationAppendResponse) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *ReplicationAppendResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

type ReplicationSyncRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Start offset to sync from
	StartOffset int64 `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// Maximum bytes to transfer
	MaxBytes      int64 `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationSyncRequest) Reset() {
	*x = ReplicationSyncRequest{}
	mi := &file_proto_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationSyncRequest) ProtoMessage() {}

func (x *ReplicationSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationSyncRequest.ProtoReflect.Descriptor instead.
func (*ReplicationSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{21}
}

func (x *ReplicationSyncRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ReplicationSyncRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ReplicationSyncRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReplicationSyncResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Events  []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	// Whether more data is available
	HasMore       bool `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationSyncResponse) Reset() {
	*x = ReplicationSyncResponse{}
	mi := &file_proto_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationSyncResponse) ProtoMessage() {}

func (x *ReplicationSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationSyncResponse.ProtoReflect.Descriptor instead.
func (*ReplicationSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{22}
}

func (x *ReplicationSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationSyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReplicationSyncResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReplicationSyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type PartitionInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Topic       string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// Current leader node ID
	LeaderId string `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// Replica node IDs
	ReplicaIds []string `protobuf:"bytes,4,rep,name=replica_ids,json=replicaIds,proto3" json:"replica_ids,omitempty"`
	// Current high watermark (last committed offset)
	HighWatermark int64 `protobuf:"varint,5,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	// Last offset in WAL
	LastOffset int64 `protobuf:"varint,6,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	// Segment count
	SegmentCount int32 `protobuf:"varint,7,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	// Disk usage in bytes
	DiskUsageBytes int64 `protobuf:"varint,8,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_proto_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{23}
}

func (x *PartitionInfo) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *PartitionInfo) GetReplicaIds() []string {
	if x != nil {
		return x.ReplicaIds
	}
	return nil
}

func (x *PartitionInfo) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

func (x *PartitionInfo) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *PartitionInfo) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *PartitionInfo) GetDiskUsageBytes() int64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

type GetPartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionRequest) Reset() {
	*x = GetPartitionRequest{}
	mi := &file_proto_events_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionRequest) ProtoMessage() {}

func (x *GetPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{24}
}

func (x *GetPartitionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // optional, list all if not specified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_proto_events_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{25}
}

func (x *ListPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_proto_events_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{26}
}

func (x *ListPartitionsResponse) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type GetWALStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWALStatusRequest) Reset() {
	*x = GetWALStatusRequest{}
	mi := &file_proto_events_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWALStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWALStatusRequest) ProtoMessage() {}

func (x *GetWALStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWALStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWALStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{27}
}

func (x *GetWALStatusRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type WALStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PartitionId  int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SegmentFiles []string               `protobuf:"bytes,2,rep,name=segment_files,json=segmentFiles,proto3" json:"segment_files,omitempty"`
	// Sparse index information
	FirstOffset  int64 `protobuf:"varint,3,opt,name=first_offset,json=firstOffset,proto3" json:"first_offset,omitempty"`
	LastOffset   int64 `protobuf:"varint,4,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	IndexEntries int64 `protobuf:"varint,5,opt,name=index_entries,json=indexEntries,proto3" json:"index_entries,omitempty"`
	// Oldest segment timestamp
	OldestSegmentTs int64 `protobuf:"varint,6,opt,name=oldest_segment_ts,json=oldestSegmentTs,proto3" json:"oldest_segment_ts,omitempty"`
	// Newest segment timestamp
	NewestSegmentTs int64 `protobuf:"varint,7,opt,name=newest_segment_ts,json=newestSegmentTs,proto3" json:"newest_segment_ts,omitempty"`
	// Disk usage
	TotalSizeBytes      int64 `protobuf:"varint,8,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	AvailableSpaceBytes int64 `protobuf:"varint,9,opt,name=available_space_bytes,json=availableSpaceBytes,proto3" json:"available_space_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WALStatus) Reset() {
	*x = WALStatus{}
	mi := &file_proto_events_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALStatus) ProtoMessage() {}

func (x *WALStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALStatus.ProtoReflect.Descriptor instead.
func (*WALStatus) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{28}
}

func (x *WALStatus) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *WALStatus) GetSegmentFiles() []string {
	if x != nil {
		return x.SegmentFiles
	}
	return nil
}

func (x *WALStatus) GetFirstOffset() int64 {
	if x != nil {
		return x.FirstOffset
	}
	return 0
}

func (x *WALStatus) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *WALStatus) GetIndexEntries() int64 {
	if x != nil {
		return x.IndexEntries
	}
	return 0
}

func (x *WALStatus) GetOldestSegmentTs() int64 {
	if x != nil {
		return x.OldestSegmentTs
	}
	return 0
}

func (x *WALStatus) GetNewestSegmentTs() int64 {
	if x != nil {
		return x.NewestSegmentTs
	}
	return 0
}

func (x *WALStatus) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *WALStatus) GetAvailableSpaceBytes() int64 {
	if x != nil {
		return x.AvailableSpaceBytes
	}
	return 0
}

type GetSchedulerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerStatusRequest) Reset() {
	*x = GetSchedulerStatusRequest{}
	mi := &file_proto_events_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerStatusRequest) ProtoMessage() {}

func (x *GetSchedulerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{29}
}

func (x *GetSchedulerStatusRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type SchedulerStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Active timing wheel slots
	ActiveTimers int64 `protobuf:"varint,2,opt,name=active_timers,json=activeTimers,proto3" json:"active_timers,omitempty"`
	// Events in ready queue
	ReadyEvents int64 `protobuf:"varint,3,opt,name=ready_events,json=readyEvents,proto3" json:"ready_events,omitempty"`
	// Scheduling delay (ms)
	AvgDelayMs int64 `protobuf:"varint,4,opt,name=avg_delay_ms,json=avgDelayMs,proto3" json:"avg_delay_ms,omitempty"`
	MaxDelayMs int64 `protobuf:"varint,5,opt,name=max_delay_ms,json=maxDelayMs,proto3" json:"max_delay_ms,omitempty"`
	// Tick configuration
	TickMs        int32 `protobuf:"varint,6,opt,name=tick_ms,json=tickMs,proto3" json:"tick_ms,omitempty"`
	WheelSize     int32 `protobuf:"varint,7,opt,name=wheel_size,json=wheelSize,proto3" json:"wheel_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerStatus) Reset() {
	*x = SchedulerStatus{}
	mi := &file_proto_events_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerStatus) ProtoMessage() {}

func (x *SchedulerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerStatus.ProtoReflect.Descriptor instead.
func (*SchedulerStatus) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{30}
}

func (x *SchedulerStatus) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *SchedulerStatus) GetActiveTimers() int64 {
	if x != nil {
		return x.ActiveTimers
	}
	return 0
}

func (x *SchedulerStatus) GetReadyEvents() int64 {
	if x != nil {
		return x.ReadyEvents
	}
	return 0
}

func (x *SchedulerStatus) GetAvgDelayMs() int64 {
	if x != nil {
		return x.AvgDelayMs
	}
	return 0
}

func (x *SchedulerStatus) GetMaxDelayMs() int64 {
	if x != nil {
		return x.MaxDelayMs
	}
	return 0
}

func (x *SchedulerStatus) GetTickMs() int32 {
	if x != nil {
		return x.TickMs
	}
	return 0
}

func (x *SchedulerStatus) GetWheelSize() int32 {
	if x != nil {
		return x.WheelSize
	}
	return 0
}

type CompactRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Compact all segments older than this timestamp
	BeforeTs int64 `protobuf:"varint,2,opt,name=before_ts,json=beforeTs,proto3" json:"before_ts,omitempty"`
	// Whether to force compaction
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_proto_events_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{31}
}

func (x *CompactRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *CompactRequest) GetBeforeTs() int64 {
	if x != nil {
		return x.BeforeTs
	}
	return 0
}

func (x *CompactRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CompactResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of segments compacted
	SegmentsCompacted int32 `protobuf:"varint,3,opt,name=segments_compacted,json=segmentsCompacted,proto3" json:"segments_compacted,omitempty"`
	// Bytes reclaimed
	BytesReclaimed int64 `protobuf:"varint,4,opt,name=bytes_reclaimed,json=bytesReclaimed,proto3" json:"bytes_reclaimed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_proto_events_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{32}
}

func (x *CompactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompactResponse) GetSegmentsCompacted() int32 {
	if x != nil {
		return x.SegmentsCompacted
	}
	return 0
}

func (x *CompactResponse) GetBytesReclaimed() int64 {
	if x != nil {
		return x.BytesReclaimed
	}
	return 0
}

type RetentionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// Max age in hours (0 = no limit)
	MaxAgeHours int32 `protobuf:"varint,2,opt,name=max_age_hours,json=maxAgeHours,proto3" json:"max_age_hours,omitempty"`
	// Max size in bytes (0 = no limit)
	MaxSizeBytes int64 `protobuf:"varint,3,opt,name=max_size_bytes,json=maxSizeBytes,proto3" json:"max_size_bytes,omitempty"`
	// Min offset to keep
	MinOffset     int64 `protobuf:"varint,4,opt,name=min_offset,json=minOffset,proto3" json:"min_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionRequest) Reset() {
	*x = RetentionRequest{}
	mi := &file_proto_events_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionRequest) ProtoMessage() {}

func (x *RetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionRequest.ProtoReflect.Descriptor instead.
func (*RetentionRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{33}
}

func (x *RetentionRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *RetentionRequest) GetMaxAgeHours() int32 {
	if x != nil {
		return x.MaxAgeHours
	}
	return 0
}

func (x *RetentionRequest) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.MaxSizeBytes
	}
	return 0
}

func (x *RetentionRequest) GetMinOffset() int64 {
	if x != nil {
		return x.MinOffset
	}
	return 0
}

type RetentionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of segments deleted
	SegmentsDeleted int32 `protobuf:"varint,3,opt,name=segments_deleted,json=segmentsDeleted,proto3" json:"segments_deleted,omitempty"`
	// Bytes freed
	BytesFreed    int64 `protobuf:"varint,4,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionResponse) Reset() {
	*x = RetentionResponse{}
	mi := &file_proto_events_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionResponse) ProtoMessage() {}

func (x *RetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionResponse.ProtoReflect.Descriptor instead.
func (*RetentionResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{34}
}

func (x *RetentionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetentionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RetentionResponse) GetSegmentsDeleted() int32 {
	if x != nil {
		return x.SegmentsDeleted
	}
	return 0
}

func (x *RetentionResponse) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

type RaftJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftJoinRequest) Reset() {
	*x = RaftJoinRequest{}
	mi := &file_proto_events_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftJoinRequest) ProtoMessage() {}

func (x *RaftJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftJoinRequest.ProtoReflect.Descriptor instead.
func (*RaftJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{35}
}

func (x *RaftJoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RaftJoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RaftJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Term          int64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftJoinResponse) Reset() {
	*x = RaftJoinResponse{}
	mi := &file_proto_events_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftJoinResponse) ProtoMessage() {}

func (x *RaftJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftJoinResponse.ProtoReflect.Descriptor instead.
func (*RaftJoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{36}
}

func (x *RaftJoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RaftJoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RaftJoinResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type RaftLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLeaveRequest) Reset() {
	*x = RaftLeaveRequest{}
	mi := &file_proto_events_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLeaveRequest) ProtoMessage() {}

func (x *RaftLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLeaveRequest.ProtoReflect.Descriptor instead.
func (*RaftLeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{37}
}

func (x *RaftLeaveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RaftLeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLeaveResponse) Reset() {
	*x = RaftLeaveResponse{}
	mi := &file_proto_events_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLeaveResponse) ProtoMessage() {}

func (x *RaftLeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLeaveResponse.ProtoReflect.Descriptor instead.
func (*RaftLeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{38}
}

func (x *RaftLeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RaftLeaveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RaftStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStatusRequest) Reset() {
	*x = RaftStatusRequest{}
	mi := &file_proto_events_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStatusRequest) ProtoMessage() {}

func (x *RaftStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStatusRequest.ProtoReflect.Descriptor instead.
func (*RaftStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{39}
}

type RaftStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Term          int64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Peers         []string               `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   int64                  `protobuf:"varint,6,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStatusResponse) Reset() {
	*x = RaftStatusResponse{}
	mi := &file_proto_events_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStatusResponse) ProtoMessage() {}

func (x *RaftStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStatusResponse.ProtoReflect.Descriptor instead.
func (*RaftStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{40}
}

func (x *RaftStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RaftStatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *RaftStatusResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftStatusResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RaftStatusResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RaftStatusResponse) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\tcronos_db\"\xd6\x02\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vschedule_ts\x18\x02 \x01(\x03R\n" +
	"scheduleTs\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12.\n" +
	"\x04meta\x18\x05 \x03(\v2\x1a.cronos_db.Event.MetaEntryR\x04meta\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x06 \x01(\x03R\tcreatedTs\x12\x16\n" +
	"\x06offset\x18\a \x01(\x03R\x06offset\x12!\n" +
	"\fpartition_id\x18\b \x01(\x05R\vpartitionId\x12\x1a\n" +
	"\bchecksum\x18\t \x01(\rR\bchecksum\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x0ePublishRequest\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.cronos_db.EventR\x05event\x12'\n" +
	"\x0fallow_duplicate\x18\x02 \x01(\bR\x0eallowDuplicate\"\x9d\x01\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\x05R\vpartitionId\x12\x1f\n" +
	"\vschedule_ts\x18\x05 \x01(\x03R\n" +
	"scheduleTs\"h\n" +
	"\x13PublishBatchRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.cronos_db.EventR\x06events\x12'\n" +
	"\x0fallow_duplicate\x18\x02 \x01(\bR\x0eallowDuplicate\"\xfd\x01\n" +
	"\x14PublishBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0fpublished_count\x18\x03 \x01(\x05R\x0epublishedCount\x12'\n" +
	"\x0fduplicate_count\x18\x04 \x01(\x05R\x0eduplicateCount\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x05R\n" +
	"errorCount\x12!\n" +
	"\ffirst_offset\x18\x06 \x01(\x03R\vfirstOffset\x12\x1f\n" +
	"\vlast_offset\x18\a \x01(\x03R\n" +
	"lastOffset\"\xfe\x01\n" +
	"\x10SubscribeRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x05R\vpartitionId\x12!\n" +
	"\fstart_offset\x18\x04 \x01(\x03R\vstartOffset\x12&\n" +
	"\x0fmax_buffer_size\x18\x05 \x01(\x05R\rmaxBufferSize\x12'\n" +
	"\x0fsubscription_id\x18\x06 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06replay\x18\a \x01(\bR\x06replay\"\xbb\x01\n" +
	"\bDelivery\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.cronos_db.EventR\x05event\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12$\n" +
	"\x0eack_timeout_ms\x18\x04 \x01(\x05R\fackTimeoutMs\x12&\n" +
	"\x05batch\x18\x05 \x03(\v2\x10.cronos_db.EventR\x05batch\"~\n" +
	"\n" +
	"AckRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vnext_offset\x18\x05 \x01(\x03R\n" +
	"nextOffset\"h\n" +
	"\vAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x10committed_offset\x18\x03 \x01(\x03R\x0fcommittedOffset\"\x99\x02\n" +
	"\rReplayRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x04 \x01(\x03R\x05endTs\x12!\n" +
	"\fstart_offset\x18\x05 \x01(\x03R\vstartOffset\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\x12%\n" +
	"\x0econsumer_group\x18\a \x01(\tR\rconsumerGroup\x12'\n" +
	"\x0fsubscription_id\x18\b \x01(\tR\x0esubscriptionId\x12\x14\n" +
	"\x05speed\x18\t \x01(\x01R\x05speed\"Z\n" +
	"\vReplayEvent\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.cronos_db.EventR\x05event\x12#\n" +
	"\rreplay_offset\x18\x02 \x01(\x03R\freplayOffset\"\xdc\x03\n" +
	"\x15ConsumerGroupMetadata\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x03(\x05R\n" +
	"partitions\x12c\n" +
	"\x11committed_offsets\x18\x04 \x03(\v26.cronos_db.ConsumerGroupMetadata.CommittedOffsetsEntryR\x10committedOffsets\x12Z\n" +
	"\x0emember_offsets\x18\x05 \x03(\v23.cronos_db.ConsumerGroupMetadata.MemberOffsetsEntryR\rmemberOffsets\x12*\n" +
	"\x11last_rebalance_ts\x18\x06 \x01(\x03R\x0flastRebalanceTs\x1aC\n" +
	"\x15CommittedOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a@\n" +
	"\x12MemberOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"m\n" +
	"\x1aCreateConsumerGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x03(\x05R\n" +
	"partitions\"M\n" +
	"\x1bCreateConsumerGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x17GetConsumerGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"1\n" +
	"\x19ListConsumerGroupsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"V\n" +
	"\x1aListConsumerGroupsResponse\x128\n" +
	"\x06groups\x18\x01 \x03(\v2 .cronos_db.ConsumerGroupMetadataR\x06groups\"Y\n" +
	"\x1dRebalanceConsumerGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\tR\tmemberIds\"\x93\x02\n" +
	"\x1eRebalanceConsumerGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12x\n" +
	"\x15partition_assignments\x18\x03 \x03(\v2C.cronos_db.RebalanceConsumerGroupResponse.PartitionAssignmentsEntryR\x14partitionAssignments\x1aG\n" +
	"\x19PartitionAssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xad\x01\n" +
	"\x18ReplicationAppendRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12(\n" +
	"\x06events\x18\x02 \x03(\v2\x10.cronos_db.EventR\x06events\x120\n" +
	"\x14expected_next_offset\x18\x03 \x01(\x03R\x12expectedNextOffset\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x03R\x04term\"\x8d\x01\n" +
	"\x19ReplicationAppendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vlast_offset\x18\x03 \x01(\x03R\n" +
	"lastOffset\x12\x1f\n" +
	"\vnext_offset\x18\x04 \x01(\x03R\n" +
	"nextOffset\"{\n" +
	"\x16ReplicationSyncRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x03R\vstartOffset\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\"\x8e\x01\n" +
	"\x17ReplicationSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x06events\x18\x03 \x03(\v2\x10.cronos_db.EventR\x06events\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x9d\x02\n" +
	"\rPartitionInfo\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vreplica_ids\x18\x04 \x03(\tR\n" +
	"replicaIds\x12%\n" +
	"\x0ehigh_watermark\x18\x05 \x01(\x03R\rhighWatermark\x12\x1f\n" +
	"\vlast_offset\x18\x06 \x01(\x03R\n" +
	"lastOffset\x12#\n" +
	"\rsegment_count\x18\a \x01(\x05R\fsegmentCount\x12(\n" +
	"\x10disk_usage_bytes\x18\b \x01(\x03R\x0ediskUsageBytes\"8\n" +
	"\x13GetPartitionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\"-\n" +
	"\x15ListPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"R\n" +
	"\x16ListPartitionsResponse\x128\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x18.cronos_db.PartitionInfoR\n" +
	"partitions\"8\n" +
	"\x13GetWALStatusRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\"\xf2\x02\n" +
	"\tWALStatus\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\rsegment_files\x18\x02 \x03(\tR\fsegmentFiles\x12!\n" +
	"\ffirst_offset\x18\x03 \x01(\x03R\vfirstOffset\x12\x1f\n" +
	"\vlast_offset\x18\x04 \x01(\x03R\n" +
	"lastOffset\x12#\n" +
	"\rindex_entries\x18\x05 \x01(\x03R\findexEntries\x12*\n" +
	"\x11oldest_segment_ts\x18\x06 \x01(\x03R\x0foldestSegmentTs\x12*\n" +
	"\x11newest_segment_ts\x18\a \x01(\x03R\x0fnewestSegmentTs\x12(\n" +
	"\x10total_size_bytes\x18\b \x01(\x03R\x0etotalSizeBytes\x122\n" +
	"\x15available_space_bytes\x18\t \x01(\x03R\x13availableSpaceBytes\">\n" +
	"\x19GetSchedulerStatusRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\"\xf8\x01\n" +
	"\x0fSchedulerStatus\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\ractive_timers\x18\x02 \x01(\x03R\factiveTimers\x12!\n" +
	"\fready_events\x18\x03 \x01(\x03R\vreadyEvents\x12 \n" +
	"\favg_delay_ms\x18\x04 \x01(\x03R\n" +
	"avgDelayMs\x12 \n" +
	"\fmax_delay_ms\x18\x05 \x01(\x03R\n" +
	"maxDelayMs\x12\x17\n" +
	"\atick_ms\x18\x06 \x01(\x05R\x06tickMs\x12\x1d\n" +
	"\n" +
	"wheel_size\x18\a \x01(\x05R\twheelSize\"f\n" +
	"\x0eCompactRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x1b\n" +
	"\tbefore_ts\x18\x02 \x01(\x03R\bbeforeTs\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x99\x01\n" +
	"\x0fCompactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x12segments_compacted\x18\x03 \x01(\x05R\x11segmentsCompacted\x12'\n" +
	"\x0fbytes_reclaimed\x18\x04 \x01(\x03R\x0ebytesReclaimed\"\x9e\x01\n" +
	"\x10RetentionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\"\n" +
	"\rmax_age_hours\x18\x02 \x01(\x05R\vmaxAgeHours\x12$\n" +
	"\x0emax_size_bytes\x18\x03 \x01(\x03R\fmaxSizeBytes\x12\x1d\n" +
	"\n" +
	"min_offset\x18\x04 \x01(\x03R\tminOffset\"\x8f\x01\n" +
	"\x11RetentionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x10segments_deleted\x18\x03 \x01(\x05R\x0fsegmentsDeleted\x12\x1f\n" +
	"\vbytes_freed\x18\x04 \x01(\x03R\n" +
	"bytesFreed\"D\n" +
	"\x0fRaftJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"V\n" +
	"\x10RaftJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x03R\x04term\"+\n" +
	"\x10RaftLeaveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"C\n" +
	"\x11RaftLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x13\n" +
	"\x11RaftStatusRequest\"\xba\x01\n" +
	"\x12RaftStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x03R\x04term\x12\x14\n" +
	"\x05peers\x18\x04 \x03(\tR\x05peers\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x06 \x01(\x03R\vlastApplied2\xdc\x02\n" +
	"\fEventService\x12@\n" +
	"\aPublish\x12\x19.cronos_db.PublishRequest\x1a\x1a.cronos_db.PublishResponse\x12O\n" +
	"\fPublishBatch\x12\x1e.cronos_db.PublishBatchRequest\x1a\x1f.cronos_db.PublishBatchResponse\x12A\n" +
	"\tSubscribe\x12\x1b.cronos_db.SubscribeRequest\x1a\x13.cronos_db.Delivery(\x010\x01\x128\n" +
	"\x03Ack\x12\x15.cronos_db.AckRequest\x1a\x16.cronos_db.AckResponse(\x010\x01\x12<\n" +
	"\x06Replay\x12\x18.cronos_db.ReplayRequest\x1a\x16.cronos_db.ReplayEvent0\x012\xde\x03\n" +
	"\x10PartitionService\x12H\n" +
	"\fGetPartition\x12\x1e.cronos_db.GetPartitionRequest\x1a\x18.cronos_db.PartitionInfo\x12U\n" +
	"\x0eListPartitions\x12 .cronos_db.ListPartitionsRequest\x1a!.cronos_db.ListPartitionsResponse\x12D\n" +
	"\fGetWALStatus\x12\x1e.cronos_db.GetWALStatusRequest\x1a\x14.cronos_db.WALStatus\x12V\n" +
	"\x12GetSchedulerStatus\x12$.cronos_db.GetSchedulerStatusRequest\x1a\x1a.cronos_db.SchedulerStatus\x12@\n" +
	"\aCompact\x12\x19.cronos_db.CompactRequest\x1a\x1a.cronos_db.CompactResponse\x12I\n" +
	"\fRunRetention\x12\x1b.cronos_db.RetentionRequest\x1a\x1c.cronos_db.RetentionResponse2\xa8\x03\n" +
	"\x14ConsumerGroupService\x12d\n" +
	"\x13CreateConsumerGroup\x12%.cronos_db.CreateConsumerGroupRequest\x1a&.cronos_db.CreateConsumerGroupResponse\x12X\n" +
	"\x10GetConsumerGroup\x12\".cronos_db.GetConsumerGroupRequest\x1a .cronos_db.ConsumerGroupMetadata\x12a\n" +
	"\x12ListConsumerGroups\x12$.cronos_db.ListConsumerGroupsRequest\x1a%.cronos_db.ListConsumerGroupsResponse\x12m\n" +
	"\x16RebalanceConsumerGroup\x12(.cronos_db.RebalanceConsumerGroupRequest\x1a).cronos_db.RebalanceConsumerGroupResponse2\xba\x01\n" +
	"\x12ReplicationService\x12S\n" +
	"\x06Append\x12#.cronos_db.ReplicationAppendRequest\x1a$.cronos_db.ReplicationAppendResponse\x12O\n" +
	"\x04Sync\x12!.cronos_db.ReplicationSyncRequest\x1a\".cronos_db.ReplicationSyncResponse0\x012\xd9\x01\n" +
	"\vRaftService\x12?\n" +
	"\x04Join\x12\x1a.cronos_db.RaftJoinRequest\x1a\x1b.cronos_db.RaftJoinResponse\x12B\n" +
	"\x05Leave\x12\x1b.cronos_db.RaftLeaveRequest\x1a\x1c.cronos_db.RaftLeaveResponse\x12E\n" +
	"\x06Status\x12\x1c.cronos_db.RaftStatusRequest\x1a\x1d.cronos_db.RaftStatusResponseB\x1bZ\x19cronos_db/pkg/types;typesb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_proto_events_proto_goTypes = []any{
	(*Event)(nil),                          // 0: cronos_db.Event
	(*PublishRequest)(nil),                 // 1: cronos_db.PublishRequest
	(*PublishResponse)(nil),                // 2: cronos_db.PublishResponse
	(*PublishBatchRequest)(nil),            // 3: cronos_db.PublishBatchRequest
	(*PublishBatchResponse)(nil),           // 4: cronos_db.PublishBatchResponse
	(*SubscribeRequest)(nil),               // 5: cronos_db.SubscribeRequest
	(*Delivery)(nil),                       // 6: cronos_db.Delivery
	(*AckRequest)(nil),                     // 7: cronos_db.AckRequest
	(*AckResponse)(nil),                    // 8: cronos_db.AckResponse
	(*ReplayRequest)(nil),                  // 9: cronos_db.ReplayRequest
	(*ReplayEvent)(nil),                    // 10: cronos_db.ReplayEvent
	(*ConsumerGroupMetadata)(nil),          // 11: cronos_db.ConsumerGroupMetadata
	(*CreateConsumerGroupRequest)(nil),     // 12: cronos_db.CreateConsumerGroupRequest
	(*CreateConsumerGroupResponse)(nil),    // 13: cronos_db.CreateConsumerGroupResponse
	(*GetConsumerGroupRequest)(nil),        // 14: cronos_db.GetConsumerGroupRequest
	(*ListConsumerGroupsRequest)(nil),      // 15: cronos_db.ListConsumerGroupsRequest
	(*ListConsumerGroupsResponse)(nil),     // 16: cronos_db.ListConsumerGroupsResponse
	(*RebalanceConsumerGroupRequest)(nil),  // 17: cronos_db.RebalanceConsumerGroupRequest
	(*RebalanceConsumerGroupResponse)(nil), // 18: cronos_db.RebalanceConsumerGroupResponse
	(*ReplicationAppendRequest)(nil),       // 19: cronos_db.ReplicationAppendRequest
	(*ReplicationAppendResponse)(nil),      // 20: cronos_db.ReplicationAppendResponse
	(*ReplicationSyncRequest)(nil),         // 21: cronos_db.ReplicationSyncRequest
	(*ReplicationSyncResponse)(nil),        // 22: cronos_db.ReplicationSyncResponse
	(*PartitionInfo)(nil),                  // 23: cronos_db.PartitionInfo
	(*GetPartitionRequest)(nil),            // 24: cronos_db.GetPartitionRequest
	(*ListPartitionsRequest)(nil),          // 25: cronos_db.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),         // 26: cronos_db.ListPartitionsResponse
	(*GetWALStatusRequest)(nil),            // 27: cronos_db.GetWALStatusRequest
	(*WALStatus)(nil),                      // 28: cronos_db.WALStatus
	(*GetSchedulerStatusRequest)(nil),      // 29: cronos_db.GetSchedulerStatusRequest
	(*SchedulerStatus)(nil),                // 30: cronos_db.SchedulerStatus
	(*CompactRequest)(nil),                 // 31: cronos_db.CompactRequest
	(*CompactResponse)(nil),                // 32: cronos_db.CompactResponse
	(*RetentionRequest)(nil),               // 33: cronos_db.RetentionRequest
	(*RetentionResponse)(nil),              // 34: cronos_db.RetentionResponse
	(*RaftJoinRequest)(nil),                // 35: cronos_db.RaftJoinRequest
	(*RaftJoinResponse)(nil),               // 36: cronos_db.RaftJoinResponse
	(*RaftLeaveRequest)(nil),               // 37: cronos_db.RaftLeaveRequest
	(*RaftLeaveResponse)(nil),              // 38: cronos_db.RaftLeaveResponse
	(*RaftStatusRequest)(nil),              // 39: cronos_db.RaftStatusRequest
	(*RaftStatusResponse)(nil),             // 40: cronos_db.RaftStatusResponse
	nil,                                    // 41: cronos_db.Event.MetaEntry
	nil,                                    // 42: cronos_db.ConsumerGroupMetadata.CommittedOffsetsEntry
	nil,                                    // 43: cronos_db.ConsumerGroupMetadata.MemberOffsetsEntry
	nil,                                    // 44: cronos_db.RebalanceConsumerGroupResponse.PartitionAssignmentsEntry
}
var file_proto_events_proto_depIdxs = []int32{
	41, // 0: cronos_db.Event.meta:type_name -> cronos_db.Event.MetaEntry
	0,  // 1: cronos_db.PublishRequest.event:type_name -> cronos_db.Event
	0,  // 2: cronos_db.PublishBatchRequest.events:type_name -> cronos_db.Event
	0,  // 3: cronos_db.Delivery.event:type_name -> cronos_db.Event
	0,  // 4: cronos_db.Delivery.batch:type_name -> cronos_db.Event
	0,  // 5: cronos_db.ReplayEvent.event:type_name -> cronos_db.Event
	42, // 6: cronos_db.ConsumerGroupMetadata.committed_offsets:type_name -> cronos_db.ConsumerGroupMetadata.CommittedOffsetsEntry
	43, // 7: cronos_db.ConsumerGroupMetadata.member_offsets:type_name -> cronos_db.ConsumerGroupMetadata.MemberOffsetsEntry
	11, // 8: cronos_db.ListConsumerGroupsResponse.groups:type_name -> cronos_db.ConsumerGroupMetadata
	44, // 9: cronos_db.RebalanceConsumerGroupResponse.partition_assignments:type_name -> cronos_db.RebalanceConsumerGroupResponse.PartitionAssignmentsEntry
	0,  // 10: cronos_db.ReplicationAppendRequest.events:type_name -> cronos_db.Event
	0,  // 11: cronos_db.ReplicationSyncResponse.events:type_name -> cronos_db.Event
	23, // 12: cronos_db.ListPartitionsResponse.partitions:type_name -> cronos_db.PartitionInfo
	1,  // 13: cronos_db.EventService.Publish:input_type -> cronos_db.PublishRequest
	3,  // 14: cronos_db.EventService.PublishBatch:input_type -> cronos_db.PublishBatchRequest
	5,  // 15: cronos_db.EventService.Subscribe:input_type -> cronos_db.SubscribeRequest
	7,  // 16: cronos_db.EventService.Ack:input_type -> cronos_db.AckRequest
	9,  // 17: cronos_db.EventService.Replay:input_type -> cronos_db.ReplayRequest
	24, // 18: cronos_db.PartitionService.GetPartition:input_type -> cronos_db.GetPartitionRequest
	25, // 19: cronos_db.PartitionService.ListPartitions:input_type -> cronos_db.ListPartitionsRequest
	27, // 20: cronos_db.PartitionService.GetWALStatus:input_type -> cronos_db.GetWALStatusRequest
	29, // 21: cronos_db.PartitionService.GetSchedulerStatus:input_type -> cronos_db.GetSchedulerStatusRequest
	31, // 22: cronos_db.PartitionService.Compact:input_type -> cronos_db.CompactRequest
	33, // 23: cronos_db.PartitionService.RunRetention:input_type -> cronos_db.RetentionRequest
	12, // 24: cronos_db.ConsumerGroupService.CreateConsumerGroup:input_type -> cronos_db.CreateConsumerGroupRequest
	14, // 25: cronos_db.ConsumerGroupService.GetConsumerGroup:input_type -> cronos_db.GetConsumerGroupRequest
	15, // 26: cronos_db.ConsumerGroupService.ListConsumerGroups:input_type -> cronos_db.ListConsumerGroupsRequest
	17, // 27: cronos_db.ConsumerGroupService.RebalanceConsumerGroup:input_type -> cronos_db.RebalanceConsumerGroupRequest
	19, // 28: cronos_db.ReplicationService.Append:input_type -> cronos_db.ReplicationAppendRequest
	21, // 29: cronos_db.ReplicationService.Sync:input_type -> cronos_db.ReplicationSyncRequest
	35, // 30: cronos_db.RaftService.Join:input_type -> cronos_db.RaftJoinRequest
	37, // 31: cronos_db.RaftService.Leave:input_type -> cronos_db.RaftLeaveRequest
	39, // 32: cronos_db.RaftService.Status:input_type -> cronos_db.RaftStatusRequest
	2,  // 33: cronos_db.EventService.Publish:output_type -> cronos_db.PublishResponse
	4,  // 34: cronos_db.EventService.PublishBatch:output_type -> cronos_db.PublishBatchResponse
	6,  // 35: cronos_db.EventService.Subscribe:output_type -> cronos_db.Delivery
	8,  // 36: cronos_db.EventService.Ack:output_type -> cronos_db.AckResponse
	10, // 37: cronos_db.EventService.Replay:output_type -> cronos_db.ReplayEvent
	23, // 38: cronos_db.PartitionService.GetPartition:output_type -> cronos_db.PartitionInfo
	26, // 39: cronos_db.PartitionService.ListPartitions:output_type -> cronos_db.ListPartitionsResponse
	28, // 40: cronos_db.PartitionService.GetWALStatus:output_type -> cronos_db.WALStatus
	30, // 41: cronos_db.PartitionService.GetSchedulerStatus:output_type -> cronos_db.SchedulerStatus
	32, // 42: cronos_db.PartitionService.Compact:output_type -> cronos_db.CompactResponse
	34, // 43: cronos_db.PartitionService.RunRetention:output_type -> cronos_db.RetentionResponse
	13, // 44: cronos_db.ConsumerGroupService.CreateConsumerGroup:output_type -> cronos_db.CreateConsumerGroupResponse
	11, // 45: cronos_db.ConsumerGroupService.GetConsumerGroup:output_type -> cronos_db.ConsumerGroupMetadata
	16, // 46: cronos_db.ConsumerGroupService.ListConsumerGroups:output_type -> cronos_db.ListConsumerGroupsResponse
	18, // 47: cronos_db.ConsumerGroupService.RebalanceConsumerGroup:output_type -> cronos_db.RebalanceConsumerGroupResponse
	20, // 48: cronos_db.ReplicationService.Append:output_type -> cronos_db.ReplicationAppendResponse
	22, // 49: cronos_db.ReplicationService.Sync:output_type -> cronos_db.ReplicationSyncResponse
	36, // 50: cronos_db.RaftService.Join:output_type -> cronos_db.RaftJoinResponse
	38, // 51: cronos_db.RaftService.Leave:output_type -> cronos_db.RaftLeaveResponse
	40, // 52: cronos_db.RaftService.Status:output_type -> cronos_db.RaftStatusResponse
	33, // [33:53] is the sub-list for method output_type
	13, // [13:33] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
